/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.MCQ_Counter;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class StartForm extends javax.swing.JFrame {

    static boolean loadBtnPressed;
    static String institute, date, sapNumber, fileNameAndPath, name;
    static int[][] qTotal = new int[50][2];
    String loadPath = "";
    static int paperCount;
    ImageIcon img = new ImageIcon(getClass().getResource("/icons/MCQ.png"));

    /**
     * Creates new form Interface1
     */
    public StartForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        date = CurrentDateTime.time();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        goButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        loadFilePathField = new javax.swing.JTextField();
        loadButton = new javax.swing.JButton();
        chooseForLoadButton = new javax.swing.JButton();
        instituteCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        sapNumberField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        saveFilePathField = new javax.swing.JTextField();
        chooseForSaveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MCQ Counter 2.0");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(51, 51, 255));
        setIconImage(img.getImage());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SAP Number");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Institute");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Create a new  MCQ Report");

        goButton.setBackground(new java.awt.Color(0, 255, 51));
        goButton.setForeground(new java.awt.Color(0, 0, 0));
        goButton.setText("Go");
        goButton.setToolTipText("<html>\n<p><strong> Create new report</strong></p>\n</html>");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("                       MCQ Counter");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("File Path");

        loadFilePathField.setEditable(false);
        loadFilePathField.setBackground(new java.awt.Color(204, 204, 204));
        loadFilePathField.setForeground(new java.awt.Color(0, 0, 0));

        loadButton.setBackground(new java.awt.Color(51, 255, 0));
        loadButton.setForeground(new java.awt.Color(0, 0, 0));
        loadButton.setText("Load");
        loadButton.setToolTipText("<html>\n<p><strong> Load previously created Report</strong></p>\n<p><strong> (That Report need to be created from this tool)</strong></p>\n</html>");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        chooseForLoadButton.setBackground(new java.awt.Color(255, 51, 0));
        chooseForLoadButton.setForeground(new java.awt.Color(0, 0, 0));
        chooseForLoadButton.setText("Choose");
        chooseForLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseForLoadButtonActionPerformed(evt);
            }
        });

        instituteCombo.setBackground(new java.awt.Color(204, 204, 204));
        instituteCombo.setForeground(new java.awt.Color(0, 0, 0));
        instituteCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDEEPA, Gampaha", "SIPWIN, Kurunegalla", "SASIP, Nugegoda" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Load an existing Report");

        sapNumberField.setBackground(new java.awt.Color(204, 204, 204));
        sapNumberField.setForeground(new java.awt.Color(0, 0, 0));
        sapNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sapNumberFieldKeyTyped(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Your Name/T Number");

        nameField.setBackground(new java.awt.Color(204, 204, 204));
        nameField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("File Path");

        saveFilePathField.setEditable(false);
        saveFilePathField.setBackground(new java.awt.Color(204, 204, 204));
        saveFilePathField.setForeground(new java.awt.Color(0, 0, 0));

        chooseForSaveButton.setBackground(new java.awt.Color(255, 51, 51));
        chooseForSaveButton.setForeground(new java.awt.Color(0, 0, 0));
        chooseForSaveButton.setText("Choose");
        chooseForSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseForSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseForSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instituteCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sapNumberField)
                            .addComponent(nameField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(loadFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chooseForLoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseForLoadButton))
                .addGap(27, 27, 27)
                .addComponent(loadButton)
                .addGap(65, 65, 65)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instituteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sapNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveFilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseForSaveButton)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(goButton)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseForLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseForLoadButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();

        jFileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter extension = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        jFileChooser.setFileFilter(extension);

        int fileState = jFileChooser.showOpenDialog(null);

        if (fileState == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jFileChooser.getSelectedFile();
            loadPath = selectedFile.getAbsolutePath();
            loadFilePathField.setText(loadPath);
        }
    }//GEN-LAST:event_chooseForLoadButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
        loadBtnPressed = true;
        if (loadPath.equals("")) {
            JOptionPane.showMessageDialog(null, "You haven't selected a file", "Eror", 2);
        } else {
            //getting data in the loading file
            fileNameAndPath = loadPath;
            try {
                File loadedFile = new File(loadPath);
                Scanner reader = new Scanner(loadedFile);
                if (reader.hasNextLine()) {
                    institute = reader.nextLine();
                    if (reader.hasNextLine()) {
                        sapNumber = reader.nextLine();
                        if (reader.hasNextLine()) {
                            date = reader.nextLine();
                            if (reader.hasNextLine()) {
                                name = reader.nextLine();
                                reader.nextLine();
                                if (institute.equals("INDEEPA, Gampaha") || institute.equals("SIPWIN, Kurunegalla") || institute.equals("SASIP, Nugegoda")) {
                                    if (reader.hasNextLine()) {
                                        for (int i = 0; i < 50; i++) {
                                            qTotal[i][0] = i + 1;
                                            reader.nextInt();
                                            qTotal[i][1] = reader.nextInt();
                                        }
                                        paperCount = reader.nextInt();
                                        reader.close();
                                        loadedFile.delete();
                                        //after getting data dumping the old file
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Invalid text File.File must be initially created by this app", "Eror", 2);
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Invalid text File.File must be initially created by this app", "Eror", 2);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid text File.File must be initially created by this app", "Eror", 2);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid text File.File must be initially created by this app", "Eror", 2);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Your text file is empty. Try creating new Report", "Eror", 2);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(StartForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            //now creating a new file  with name, sap number, date (and more) acquired from the previously loaded (now dumped) file
            try {
                File newFile = new File(fileNameAndPath);
                if (newFile.createNewFile()) {
                    System.out.println("File created: " + newFile.getName());
                    try {
                        FileWriter Writer = new FileWriter(fileNameAndPath);
                        Writer.write(institute + "\n" + sapNumber + "\n" + date + "\n" + name + "\n\n");
                        Writer.close();
                        System.out.println("Successfully written.");
                        MCQ_Counter form = new MCQ_Counter();
                        form.setVisible(true);
                        form.pack();
                        this.dispose();
                    } catch (IOException e) {
                        System.out.println("An error has occurred.Nothing written");
                        e.printStackTrace();
                    }
                } else {
                    System.out.println("Unable to Load File");
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_loadButtonActionPerformed

    private void sapNumberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sapNumberFieldKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_sapNumberFieldKeyTyped

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        loadBtnPressed = false;
        if (!sapNumberField.getText().equals("") && !nameField.getText().equals("") && !saveFilePathField.getText().equals("")) {
            institute = String.valueOf(instituteCombo.getSelectedItem());
            sapNumber = sapNumberField.getText();
            name = nameField.getText();
            fileNameAndPath = saveFilePathField.getText();
            try {
                File newFile = new File(fileNameAndPath);
                if (newFile.createNewFile()) {
                    System.out.println("File created: " + newFile.getName());
                    try {
                        FileWriter Writer = new FileWriter(fileNameAndPath);
                        Writer.write(institute + "\n" + sapNumber + "\n" + date + "\n" + name + "\n\n");
                        Writer.close();
                        System.out.println("Successfully written.");
                        MCQ_Counter form = new MCQ_Counter();
                        form.setVisible(true);
                        form.pack();
                        this.dispose();
                    } catch (IOException e) {
                        System.out.println("An error has occurred.Nothing written");
                        e.printStackTrace();
                    }
                } else {
                    System.out.println("File already exists.");
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Some Fields or Selections are empty", "Eror", 2);
        }

    }//GEN-LAST:event_goButtonActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseDragged

    private void chooseForSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseForSaveButtonActionPerformed
        // TODO add your handling code here:
        if (!sapNumberField.getText().equals("") && !nameField.getText().equals("")) {
            institute = String.valueOf(instituteCombo.getSelectedItem());
            sapNumber = sapNumberField.getText();
            name = nameField.getText();
            JFileChooser jFileChooser = new JFileChooser();

            jFileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));

            jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

            int fileState = jFileChooser.showDialog(null, "Select Folder");

            if (fileState == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jFileChooser.getSelectedFile();
                fileNameAndPath = selectedFile.getAbsolutePath() + "\\" + name + "-Report of " + institute + "  Sap " + sapNumber + " MCQ " + date + ".txt";
                saveFilePathField.setText(fileNameAndPath);
                System.out.println(fileNameAndPath);
            }
        } else {
            JOptionPane.showMessageDialog(null, "You need to complete above fields before choosing the file saving directory", "Warning", 2);
        }
    }//GEN-LAST:event_chooseForSaveButtonActionPerformed

    public String returnInstitute() {
        return institute;
    }

    public String returnSapNumber() {
        return sapNumber;
    }

    public String returnDate() {
        return date;
    }

    public String returnFileNameAndPath() {
        return fileNameAndPath;
    }

    public String returnName() {
        return name;
    }

    public int[][] returnQTotal() {
        return qTotal;
    }

    public int returnPaperCount() {
        return paperCount;
    }

    public boolean returnLoadPressed() {
        return loadBtnPressed;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseForLoadButton;
    private javax.swing.JButton chooseForSaveButton;
    private javax.swing.JButton goButton;
    private javax.swing.JComboBox<String> instituteCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loadButton;
    private javax.swing.JTextField loadFilePathField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField sapNumberField;
    private javax.swing.JTextField saveFilePathField;
    // End of variables declaration//GEN-END:variables
}
